name: Test MiraiOK

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test-send-message:
    if: false # temporary stopping this workflow
    name: Test Send Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd "${{ secrets.REPO_PATH }}"
            git fetch --all
            git reset --hard origin/dev
            sudo docker-compose up -d --build --force-recreate
